apiVersion: v1
kind: Pod
metadata:
  name: python
  namespace: vineyard-system
spec:
  containers:
  - name: python
    image: python:3.10
    command: ["python", "-c", "import time; time.sleep(100000)"]