# Default values for vineyard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vineyardcloudnative/vineyard-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.9.0"

serviceAccountName: "vineyard-manager"

service:
  type: ClusterIP
  port: 9600

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

tolerations:
  {}
  # this toleration is to have the daemonset runnable on master nodes
  # remove it if your masters can't run pods.
  # - key: node-role.kubernetes.io/master
  #   effect: NoSchedule

affinity: {}
