apiVersion: batch/v1
kind: Job
metadata:
  name: vineyard-recover
  namespace: vineyard-system
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vineyard-recover
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - vineyard-system-vineyard-operator-cert-manager
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - vineyard-recover
              topologyKey: kubernetes.io/hostname
      containers:
        - name: engine
          image: ghcr.io/v6d-io/v6d/recover-job
          imagePullPolicy: IfNotPresent
          env:
            - name: RECOVER_PATH
              value: ""
            - name: ENDPOINT
              value: vineyard-operator-cert-manager-rpc.vineyard-system
            - name: SELECTOR
              value: vineyard-recover
            - name: ALLINSTANCES
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: vineyard-sock
              mountPath: /var/run
            - name: recover-path
              mountPath: "/var/vineyard/dump"
      restartPolicy: Never
      volumes:
        - name: vineyard-sock
          hostPath:
            path: /var/run/vineyard-kubernetes/vineyard-system/vineyard-operator-cert-manager
        - name: recover-path
          persistentVolumeClaim:
            claimName: vineyard-backup
  ttlSecondsAfterFinished: 80
