version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  static_hosting:
    e2e-tests-assembly-local-logs:
      metadata:
        name: ""
      path: e2e-tests-assembly-local-logs
      file_viewer: true